In [20]:
import numpy as np 
from typing import Callable 

def sigmoid(n:np.ndarray)->np.ndarray:
    return 1/(1+np.exp(-n))

def deepleraning(
        X:np.ndarray,
        W:np.ndarray,
) -> np.ndarray:
    s = sigmoid(np.dot(X, W))
    return s

def deriv(
        func:Callable[[np.ndarray], np.ndarray],
        input :np.ndarray,
        delta : float = 0.001
) -> np.ndarray:
    return (func(input + delta) - func(input - delta)) / (2 * delta)


In [21]:
def matrix_backward(
        X : np.ndarray,
        W : np.ndarray,
        ):
    N = np.dot(X,W )
    S = sigmoid(N)
    dsdn = deriv(sigmoid, N)
    dndx = np.transpose(W , (1,0))
    return np.dot(dsdn, dndx)

In [ ]:
x = np.array([1, 2, 3])
w = np.array([1, 2, 3])
print(matrix_backward(x, w))

In [25]:
import numpy as np

# Define the activation function (ReLU)
def relu(x):
    """
    ReLU activation function: outputs the input if positive, else outputs 0.
    """
    return np.maximum(0, x)

# Define the softmax function for the output layer
def softmax(x):
    """
    Softmax function: converts raw output scores into probabilities.
    """
    exp_x = np.exp(x - np.max(x))  # For numerical stability
    return exp_x / exp_x.sum(axis=1, keepdims=True)

# Define a function for the forward pass through the network
def forward_pass(X, W1, b1, W2, b2):
    """
    Perform a forward pass through the network with one hidden layer.
    
    Args:
    X (numpy.ndarray): Input data, shape (number of samples, input size).
    W1 (numpy.ndarray): Weights for the input to hidden layer, shape (input size, hidden size).
    b1 (numpy.ndarray): Bias for the hidden layer, shape (1, hidden size).
    W2 (numpy.ndarray): Weights for the hidden to output layer, shape (hidden size, output size).
    b2 (numpy.ndarray): Bias for the output layer, shape (1, output size).
    
    Returns:
    numpy.ndarray: The output probabilities after the softmax layer.
    """
    # Input to Hidden Layer
    Z1 = np.dot(X, W1) + b1  # Linear transformation
    A1 = relu(Z1)            # Apply ReLU activation function
    
    # Hidden to Output Layer
    Z2 = np.dot(A1, W2) + b2  # Linear transformation
    A2 = softmax(Z2)          # Apply softmax activation function
    
    return A2

# Example usage of the forward pass function

# Initialize model parameters
input_size = 3    # Number of features in input layer
hidden_size = 5   # Number of neurons in hidden layer
output_size = 2   # Number of neurons in output layer

# Random weights and biases
W1 = np.random.randn(input_size, hidden_size)  # Input to Hidden layer weights
b1 = np.zeros((1, hidden_size))                 # Hidden layer biases
W2 = np.random.randn(hidden_size, output_size)  # Hidden to Output layer weights
b2 = np.zeros((1, output_size))                 # Output layer biases

# Example input data (e.g., 4 samples, each with 3 features)
X = np.array([[0.1, 0.2, 0.3],
              [0.4, 0.5, 0.6],
              [0.7, 0.8, 0.9],
              [0.9, 0.8, 0.7]])

# Perform the forward pass and get the output probabilities
output = forward_pass(X, W1, b1, W2, b2)
print("Output probabilities:\n", output)
print(W1)
print(b1)
print(W2)
print(b2)

Output probabilities:
 [[0.63409856 0.36590144]
 [0.82693875 0.17306125]
 [0.92945382 0.07054618]
 [0.94432689 0.05567311]]
[[ 0.71447704 -0.6195086  -0.61722846  1.27900419 -0.59244548]
 [-1.33690299 -0.70783088  2.10454951  1.74741381  1.04562265]
 [-0.86602243 -0.45971182  0.80909576  1.01121817  0.19528604]]
[[0. 0. 0. 0. 0.]]
[[ 1.33856171 -0.76595421]
 [-0.0273734  -1.13469917]
 [ 0.29962165  1.00253266]
 [ 1.16490248 -0.05855042]
 [-1.64302799 -1.72805124]]
[[0. 0.]]
