In [3]:
import numpy as np 


X = np.random.randint(1, 100, size = (20000, 5))
Y = np.random.randint(1,100, size = (20000,1))


#b = np.random.rand(1,1)
w = np.random.rand(5,1)

#ensuring X Y , w had the same cols, so it can works
assert X.shape[0] == Y.shape[0]
assert X.shape[1] == w.shape[0]

#Start Multiplying it 
N = np.dot(X, w)
squaredDifferetiaion = np.power(Y - N, 2)
mse = np.mean(squaredDifferetiaion)

#Computing derivatives of loss func respected to N
dldn = -2 * (Y - N)
dldn
#Computing derivatives of N respected to weight
dndw = X.T
dndw
#Computing derivatives of loss function respected to weights
dldw = np.dot(dndw, dldn)

In [4]:
mse

np.float64(1063.272492464277)

In [ ]:
#Data initialization 
import numpy as np
def dataPreps(Data_x, TargetValue) :
    Data_x = np.array(X)
    TargetValue = np.array(TargetValue) 
    
    assert Data_x.shape[0] == TargetValue.shape[0]
    assert Data_x.shape[0] != 0
    if len(Data_x.shape) < 2 : 
        m = Data_x.shape[0]
        Data_x = Data_x.reshape(m, -1)
    return Data_x, TargetValue

def lossFunctions (PredictedValue, OriginalValue) : 
    squaredDifferetiaion = np.power(OriginalValue - PredictedValue, 2)
    return np.mean(squaredDifferetiaion)

def train (Data_x : ndarray, TargetValue : ndarray,
           weightMatrices) : 
    #Start Multiplying it 
    N = np.dot(Data_x, w)
    return N

In [5]:
dldw = np.dot(dndw, dldn)
dldw

array([[15961130.12643526],
       [17548138.51413631],
       [ 8702211.23596885],
       [10038825.64772005],
       [14278568.67991061]])

In [6]:
w

array([[0.30781362],
       [0.34779024],
       [0.05902859],
       [0.11067256],
       [0.24306984]])

In [7]:
w_new = (w-0.001) * dldw
w_new

array([[4897092.09312988],
       [6085523.2119932 ],
       [ 504977.04116443],
       [1100983.73115254],
       [3456410.84121365]])